/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package gulo.schema;

import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class OrganizationDatasetEdge implements org.apache.thrift.TBase<OrganizationDatasetEdge, OrganizationDatasetEdge._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("OrganizationDatasetEdge");

  private static final org.apache.thrift.protocol.TField ORGANIZATION_FIELD_DESC = new org.apache.thrift.protocol.TField("organization", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField DATASET_FIELD_DESC = new org.apache.thrift.protocol.TField("dataset", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new OrganizationDatasetEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new OrganizationDatasetEdgeTupleSchemeFactory());
  }

  public OrganizationID organization; // required
  public DatasetID dataset; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ORGANIZATION((short)1, "organization"),
    DATASET((short)2, "dataset");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ORGANIZATION
          return ORGANIZATION;
        case 2: // DATASET
          return DATASET;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ORGANIZATION, new org.apache.thrift.meta_data.FieldMetaData("organization", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OrganizationID.class)));
    tmpMap.put(_Fields.DATASET, new org.apache.thrift.meta_data.FieldMetaData("dataset", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DatasetID.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(OrganizationDatasetEdge.class, metaDataMap);
  }

  public OrganizationDatasetEdge() {
  }

  public OrganizationDatasetEdge(
    OrganizationID organization,
    DatasetID dataset)
  {
    this();
    this.organization = organization;
    this.dataset = dataset;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public OrganizationDatasetEdge(OrganizationDatasetEdge other) {
    if (other.isSetOrganization()) {
      this.organization = new OrganizationID(other.organization);
    }
    if (other.isSetDataset()) {
      this.dataset = new DatasetID(other.dataset);
    }
  }

  public OrganizationDatasetEdge deepCopy() {
    return new OrganizationDatasetEdge(this);
  }

  @Override
  public void clear() {
    this.organization = null;
    this.dataset = null;
  }

  public OrganizationID getOrganization() {
    return this.organization;
  }

  public OrganizationDatasetEdge setOrganization(OrganizationID organization) {
    this.organization = organization;
    return this;
  }

  public void unsetOrganization() {
    this.organization = null;
  }

  /** Returns true if field organization is set (has been assigned a value) and false otherwise */
  public boolean isSetOrganization() {
    return this.organization != null;
  }

  public void setOrganizationIsSet(boolean value) {
    if (!value) {
      this.organization = null;
    }
  }

  public DatasetID getDataset() {
    return this.dataset;
  }

  public OrganizationDatasetEdge setDataset(DatasetID dataset) {
    this.dataset = dataset;
    return this;
  }

  public void unsetDataset() {
    this.dataset = null;
  }

  /** Returns true if field dataset is set (has been assigned a value) and false otherwise */
  public boolean isSetDataset() {
    return this.dataset != null;
  }

  public void setDatasetIsSet(boolean value) {
    if (!value) {
      this.dataset = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ORGANIZATION:
      if (value == null) {
        unsetOrganization();
      } else {
        setOrganization((OrganizationID)value);
      }
      break;

    case DATASET:
      if (value == null) {
        unsetDataset();
      } else {
        setDataset((DatasetID)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ORGANIZATION:
      return getOrganization();

    case DATASET:
      return getDataset();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ORGANIZATION:
      return isSetOrganization();
    case DATASET:
      return isSetDataset();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof OrganizationDatasetEdge)
      return this.equals((OrganizationDatasetEdge)that);
    return false;
  }

  public boolean equals(OrganizationDatasetEdge that) {
    if (that == null)
      return false;

    boolean this_present_organization = true && this.isSetOrganization();
    boolean that_present_organization = true && that.isSetOrganization();
    if (this_present_organization || that_present_organization) {
      if (!(this_present_organization && that_present_organization))
        return false;
      if (!this.organization.equals(that.organization))
        return false;
    }

    boolean this_present_dataset = true && this.isSetDataset();
    boolean that_present_dataset = true && that.isSetDataset();
    if (this_present_dataset || that_present_dataset) {
      if (!(this_present_dataset && that_present_dataset))
        return false;
      if (!this.dataset.equals(that.dataset))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_organization = true && (isSetOrganization());
    builder.append(present_organization);
    if (present_organization)
      builder.append(organization);

    boolean present_dataset = true && (isSetDataset());
    builder.append(present_dataset);
    if (present_dataset)
      builder.append(dataset);

    return builder.toHashCode();
  }

  public int compareTo(OrganizationDatasetEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    OrganizationDatasetEdge typedOther = (OrganizationDatasetEdge)other;

    lastComparison = Boolean.valueOf(isSetOrganization()).compareTo(typedOther.isSetOrganization());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrganization()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.organization, typedOther.organization);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDataset()).compareTo(typedOther.isSetDataset());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDataset()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dataset, typedOther.dataset);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("OrganizationDatasetEdge(");
    boolean first = true;

    sb.append("organization:");
    if (this.organization == null) {
      sb.append("null");
    } else {
      sb.append(this.organization);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("dataset:");
    if (this.dataset == null) {
      sb.append("null");
    } else {
      sb.append(this.dataset);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (organization == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'organization' was not present! Struct: " + toString());
    }
    if (dataset == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'dataset' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class OrganizationDatasetEdgeStandardSchemeFactory implements SchemeFactory {
    public OrganizationDatasetEdgeStandardScheme getScheme() {
      return new OrganizationDatasetEdgeStandardScheme();
    }
  }

  private static class OrganizationDatasetEdgeStandardScheme extends StandardScheme<OrganizationDatasetEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, OrganizationDatasetEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ORGANIZATION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.organization = new OrganizationID();
              struct.organization.read(iprot);
              struct.setOrganizationIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DATASET
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.dataset = new DatasetID();
              struct.dataset.read(iprot);
              struct.setDatasetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, OrganizationDatasetEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.organization != null) {
        oprot.writeFieldBegin(ORGANIZATION_FIELD_DESC);
        struct.organization.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.dataset != null) {
        oprot.writeFieldBegin(DATASET_FIELD_DESC);
        struct.dataset.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class OrganizationDatasetEdgeTupleSchemeFactory implements SchemeFactory {
    public OrganizationDatasetEdgeTupleScheme getScheme() {
      return new OrganizationDatasetEdgeTupleScheme();
    }
  }

  private static class OrganizationDatasetEdgeTupleScheme extends TupleScheme<OrganizationDatasetEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, OrganizationDatasetEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.organization.write(oprot);
      struct.dataset.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, OrganizationDatasetEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.organization = new OrganizationID();
      struct.organization.read(iprot);
      struct.setOrganizationIsSet(true);
      struct.dataset = new DatasetID();
      struct.dataset.read(iprot);
      struct.setDatasetIsSet(true);
    }
  }

}

